### ISSUE TITLE
Add Illustrator File Support

### ISSUE THREAD

**Issue by aaronf81** [mike-edel/ID-MultiPageImporter#2]
It would be great to add the following capabilities: 

1. Edit script to accept Adobe Illustrator files (multi-artboard). With option to change layer visibility & which artboards (page numbers) to be imported. 
2. Added bonus would be to be able to select multiple files for import at once (this would probably not work with layer / page option as each file would be different).

**Comment by aaronf81** [comment]
The select file dialogue window that comes up is still only allowing PDF or INDD files... the AI files are still greyed out (Indesign 2019 & 2018 on mac).

**Comment by aaronf81** [comment]
I did download this version, code looks good up front but looks like something around code line 103 & 1470 (if I had to guess)... I really don't know jsx well.. but looks like that's the hang up it's still calling only PDF and INDD for mac.

**Comment by mike-edel** [comment]
Ah, I apparently only added the windows specific code.

**Comment by mike-edel** [comment]
This will be a bit tricky as I don't have a mac to test but let's see...

**Comment by mike-edel** [comment]
ok, updated the mac side - should be fine

**Comment by aaronf81** [comment]
I added " || fileToTest.name.indexOf(".ai") > -1"  to line 1473 and 1614 ... seems to work now.. 
but I see you just did the same! 

Other issue, is there a way to have it start import on currently selected page rather than starting at beginning of the document?

**Comment by mike-edel** [comment]
ok, cool
1473 and 1614 checks are different though:
1473 checks if >1
1614 checks if !=-1

start page is separate issue but you can at least tell it on which ID page to start in the dialog: ![2018-10-26_19h43_45](https://user-images.githubusercontent.com/22517839/47583377-8b76c900-d957-11e8-880c-b390451a8334.png)

**Comment by mike-edel** [comment]
If you want some kind of "start placing on current Doc Page" option feel free to open another issue for that. Can't promise I will be able to do it - this is the first time this comes up.

**Comment by mike-edel** [comment]
same for your second request from above - it's easier to handle feature requests if it's only one major feature per issue. Makes it easy to link code changes and releases with feature requests/issues.

**Comment by aaronf81** [comment]
ahhhh Thanks!! I missed that selection option. You rock! Thank you thank you thank you!! 
I'm new to scripting and GitHub, so please excuse my nube'ness

**Comment by mike-edel** [comment]
Not an expert myself. We ended up needing the script so much that I kind of volunteered to add required fixes. ;)

**Comment by mike-edel** [comment]
@aaronf81 do you have any update on whether this works for you? I didn't have any time to test myself but would be good to know if it is something I can share with other users.
Cheers,

Mike

**Comment by aaronf81** [comment]
@mike-edel Seems to be working great! My team has been using it for a week or so and seems to have no issues. The only catch is the illustrator files must be saved with "Create PDF compatible file" check box ticked in save dialogue. Thank you again!!

**Comment by aaronf81** [comment]
Of note (but has no effect on functionality) the dialogue box says "Select a PDF or InDesign file to place." You might consider changing to "Select a PDF, InDesign File, or PDF Compatible Illustrator File to place."

**Comment by mike-edel** [comment]
Good point, will take a look at it on the weekend.

**Comment by mike-edel** [comment]
Fixed in ba54dc2

**Comment by mike-edel** [comment]
Merged into Master. Will close this as "done" for now. If you run into issues please open a new issue.
Thanks again for the suggestion - great idea!
