### ISSUE TITLE
MultiPageImporter doesn't work on AI 16.2.1 (MacOS Big Sur 11.6)

### ISSUE THREAD

**Issue by Montbernage** [mike-edel/ID-MultiPageImporter#20]
Hi,
I have installed version v2.6.4 in the user directory (AI 16.2.1 / MacOS Big Sur 11.6) and when I click on the script the dialog window does not open.
Do you have an idea?
Thank you and have a nice day.
Best.

**Comment by mike-edel** [comment]
I assume you put it in the Indesign user scripts folder and not AI like you wrote 😉
There was a similar report before but the user didn't get back to me with more details.
Hard to troubleshoot on my end as I don't have access to a Mac for testing. Sounds a bit like a permissions issue - the script tries to read / write a config file in the same folder.
Is there a way to exclude that folder from the file system protection?

**Comment by Montbernage** [comment]
Hi Mike,

Sorry for the late reply. I couldn't find anything about permissions but
that's probably where the problem is. However, I did some testing and found
a solution that works. I put the script in the "Community/Script Panel"
directory rather than in "user" (where the script does not run). There, the
script opens. However, it is impossible to navigate in the directories in
"column" view (the folders are greyed out). You can do this by switching to
"list" view and unfolding the folders to access the pdf file to be imported.
Another thing. I was thinking that it would be great to have an option for
the script to create the necessary pages in the Indesign file according to
the number of pages in the pdf (like "PlaceMultipagePDF.jsx" does in
Scripts/Scripts Panel/Samples/).

I hope this helps.
And thanks for your script which is great.

Best,
Emmanuel
