### ISSUE TITLE
How can I contact mike-edel directly?

### ISSUE THREAD

**Issue by mw-shublaq** [mike-edel/ID-MultiPageImporter#22]
I, I wanna contact you directly for working on some small-medium script for Adobe InDesign, 

Can you provide your email?

**Comment by mike-edel** [comment]
Hi Muhammad,

I'm sorry but I hardly find enough time to keep updating this script.
There is actually a good chance that the script you are looking for already exists in some form.
What is it that you need to do?
I'd suggest asking around in the scripting community on the Adobe forums: https://community.adobe.com/t5/indesign/ct-p/ct-indesign?page=1&sort=latest_replies&filter=all&tabid=discussions&topics=label-scripting

Best,
Mike
