### ISSUE TITLE
PDF with Trim, Art, Bleed page boxes or Media fails to import with error "[PDF]" doesn't contain [Page Box] crop type

### ISSUE THREAD

**Issue by ll-546** [mike-edel/ID-MultiPageImporter#24]
Macbook Pro, M1 Max, Monterey, InDesign 16.4

When trying to import a PDF that was freshly exported from an InDesign file that contains all page boxes, the error "[PDF]" doesn't contain [Page Box] crop type appears and script doesn't run. Even selecting "Media" fails to import with the same message. 

This is happening to multiple PDFs 2GB or larger with CMYK art. Is there a size limit for this script?

Thanks!

**Comment by mike-edel** [comment]
A quick search found a [forum post ](https://community.adobe.com/t5/indesign-discussions/linked-file-size-limits/td-p/11600839)that indicates this is indeed a size limit of InDesign. What happens if you place the file manually?
