### ISSUE TITLE
Does not run in ID 2019 14.0.2

### ISSUE THREAD

**Issue by artorious83** [mike-edel/ID-MultiPageImporter#7]
Love this script! Thank you so much for creating it! Glad I kept my ID 2017 version because it runs fine there, but for some reason it doesn't want to run in 2019. Thanks again!

**Comment by mike-edel** [comment]
Thanks for the nice words but I didn't create it. Just picked it up and tried to maintain it. ☺️
Which is why I find your comment interesting. Last time I checked it was working fine in current indesign versions. Let me check again to be sure.
Cheers, Mike 

On September 10, 2019 6:18:27 PM GMT+02:00, artorious83 <notifications@github.com> wrote:
>Love this script! Thank you so much for creating it! Glad I kept my ID
>2017 version because it runs fine there, but for some reason it doesn't
>want to run in 2019. Thanks again!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mike-edel/ID-MultiPageImporter/issues/7

-- 
 Sent from my mobile device

**Comment by mike-edel** [comment]
Ok, will take a look tomorrow.

**Comment by mike-edel** [comment]
Just checked - works fine for me in 14.03.
@matt21218 @artorious83 : can you please run a basic test?
- check the [latest version ](https://github.com/mike-edel/ID-MultiPageImporter/releases/tag/v2.6.2)of the script, install into user scripts folder (not program files)
on Windows that would be `%appdata%\Adobe\InDesign\Version 14.0\en_US\Scripts\Scripts Panel`
- open a new document (I used the blank A4 template)
- place known good simple pdf document with similar size
If that still gives you issues we'll need to check the details.

**Comment by matt21218** [comment]
Hi Mike, I just tried it again and it still doesn't work. I just get
spinning beach ball and it doesn't take me to the dialog box anymore. I
specifically tried using one of the PDF files that had worked in the past,
and for some reason it now refuses to work, which doesn't make any sense.

Matt

**Comment by matt21218** [comment]
I am using the same version of indesign that you are using.

**Comment by mike-edel** [comment]
Just wondering whether this might be related to Mac OS...
Did you run any updates in between? I could very well imagine that there were changes to access models or so. Hard to test on my side as I'm on windows.
Cheers, Mike 

On September 17, 2019 4:17:21 PM GMT+02:00, matt21218 <notifications@github.com> wrote:
>Hi Mike, I just tried it again and it still doesn't work. I just get
>spinning beach ball and it doesn't take me to the dialog box anymore. I
>specifically tried using one of the PDF files that had worked in the
>past,
>and for some reason it now refuses to work, which doesn't make any
>sense.
>
>Matt
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mike-edel/ID-MultiPageImporter/issues/7#issuecomment-532241536

-- 
 Sent from my mobile device

**Comment by cdaters** [comment]
> Just wondering whether this might be related to Mac OS... Did you run any updates in between? I could very well imagine that there were changes to access models or so. Hard to test on my side as I'm on windows. Cheers, Mike

@mike-edel, I am running this on macOS, in InDesign 2021. It doesn't even initiate.

I am looking at in in ExtendScript Toolkit and trying to run it there. it immediately errors, giving me "Cannot execute script in target engine 'main'. The details of which are "Cannot execute script in target engine 'main'! (#1116) Can't start debug session." if that is helpful?

When I click okay, it takes me to line 87 of the script which is:
`prefsFile = File((Folder(app.activeScript)).parent + "/MultiPageImporterPrefs2.5.txt");`
Not sure if this is helpful, but there you go ;-)

**Comment by mike-edel** [comment]
Looking at this again it might be a permissions issue on Mac. The code on line 87 requests read/write file access to the config file where the last used settings are stored. 

I only have Windows and I always run the script in my user profile folder so every application will have write permission even without running as admin.
@cdaters where do you store and run the script - user folder or somewhere in the application folder?

**Comment by cdaters** [comment]
I am loading it into my user profile folder. I will revisit this again soon and let you know what I discover. macOS is getting more "security" minded with everything with their latest "Big Sur" update, so I would not be surprised. I have yet to try it on my PC, that would require installing everything over there, lol and I had been in a rush that day.

**Comment by mike-edel** [comment]
@cdaters I just stumbled over a thread in the Adobe forums that might help explain this. The user pointed out that he had issues on his system and was able to narrow it down to the `#target indesign` line in the script. That line normally makes the ExtendScript editor run the script inside the latest version of InDesign when debugging but is not important otherwise.
So I removed it in the latest version - can you pleas test this?
