### ISSUE TITLE
Placing more then one imported page per new document page.

### ISSUE THREAD

**Issue by DL-BL** [mike-edel/ID-MultiPageImporter#8]
First off, thanks a lot for maintaining the script!!

Now the issue:
I have to import large Indesign documents into a new document, where the new document should have 4 A6 pages per A4 page.
So, I would like to have a script to place 4 (reduced) A4 pages per A4 page before generating a new page.
So there would have to be like a mini template where the number of pages and location/scale of the pages could be defined (per new page)... Is souch a thing even possible?

Cheers!
Daniel

**Comment by mike-edel** [comment]
Hi Daniel,

I wonder if you couldn't get this to work differently. I know I had a similar feature on the imposition software of our xerox color printer.
Let me think about it...

On October 16, 2019 9:12:09 AM GMT+02:00, DL-BL <notifications@github.com> wrote:
>First off, thanks a lot for maintaining the script!!
>
>Now the issue:
>I have to import large Indesign documents into a new document, where
>the new document should have 4 A6 pages per A4 page.
>So, I would like to have a script to place 4 (reduced) A4 pages per A4
>page before generating a new page.
>So there would have to be like a mini template where the number of
>pages and location/scale of the pages could be defined (per new
>page)... Is souch a thing even possible?
>
>Cheers!
>Daniel
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mike-edel/ID-MultiPageImporter/issues/8

-- 
 Sent from my mobile device

**Comment by DL-BL** [comment]
Hi Mike

 

I tried the imposition feature in Indesign, but its limited to very few templates, so that is a no go unfortunately…

 

And I also searched for other scripts and plug ins… but turned up empty so far.

 

So what ever might come up on your side, I thank you for the effort!!

 

 

 

Von: Mike <notifications@github.com>
Antworten an: mike-edel/ID-MultiPageImporter <reply@reply.github.com>
Datum: Donnerstag, 17. Oktober 2019 um 08:06
An: mike-edel/ID-MultiPageImporter <ID-MultiPageImporter@noreply.github.com>
Cc: Daniel Lauber <d.lauber@datacomm.ch>, Author <author@noreply.github.com>
Betreff: Re: [mike-edel/ID-MultiPageImporter] Placing more then one imported page per new document page. (#8)

 

Hi Daniel,

I wonder if you couldn't get this to work differently. I know I had a similar feature on the imposition software of our xerox color printer.
Let me think about it...

On October 16, 2019 9:12:09 AM GMT+02:00, DL-BL <notifications@github.com> wrote:
>First off, thanks a lot for maintaining the script!!
>
>Now the issue:
>I have to import large Indesign documents into a new document, where
>the new document should have 4 A6 pages per A4 page.
>So, I would like to have a script to place 4 (reduced) A4 pages per A4
>page before generating a new page.
>So there would have to be like a mini template where the number of
>pages and location/scale of the pages could be defined (per new
>page)... Is souch a thing even possible?
>
>Cheers!
>Daniel
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mike-edel/ID-MultiPageImporter/issues/8

-- 
Sent from my mobile device

**Comment by mike-edel** [comment]
I think I found a workaround but whether it works for you probably depends on how many pages you have to place.

Step 1: split source A4 pdf into **4** sources - 1 for each quadrant. 
Easiest way I found so far is by zooming out in the Organize Pages view of Acrobat Pro until you see 4 columns of pages. Drag a selection down until you have the whole column selected.
Extract those selected pages as a new pdf. Repeat that for all 4 columns:

![image](https://user-images.githubusercontent.com/22517839/67151424-5846eb80-f2c6-11e9-8a16-861b03e0c3dc.png)

Result: 
![image](https://user-images.githubusercontent.com/22517839/67151448-abb93980-f2c6-11e9-868f-34601770a9fa.png)

Step 2: place using MultipageImporter (once for each quadrant)
Set scale to 50%
place first column in top left
second column in top right
and so on:
![image](https://user-images.githubusercontent.com/22517839/67151482-208c7380-f2c7-11e9-80b2-9a2d5d479077.png)
I generally prefer to create a new layer for each pdf so I can easily get rid of it if something goes wrong.
Result:
![image](https://user-images.githubusercontent.com/22517839/67151518-ac9e9b00-f2c7-11e9-937e-2c58a73a4500.png)

Would be great to know if this helps.
Cheers, Mike

**Comment by mike-edel** [comment]
ps: implementing this could become pretty tricky - and this is more or less the first time I get asked about it.

**Comment by DL-BL** [comment]
WOW!

 

Hi mike

 

That looks interesting! I’ll give it a try and mail you back.

Thanks a lot!

 

I don’t work on Mondays though, so you’ll have to wait till Tuesday…

 

Cheers!

Daniel

 

 

Von: Mike <notifications@github.com>
Antworten an: mike-edel/ID-MultiPageImporter <reply@reply.github.com>
Datum: Samstag, 19. Oktober 2019 um 23:26
An: mike-edel/ID-MultiPageImporter <ID-MultiPageImporter@noreply.github.com>
Cc: Daniel Lauber <d.lauber@datacomm.ch>, Author <author@noreply.github.com>
Betreff: Re: [mike-edel/ID-MultiPageImporter] Placing more then one imported page per new document page. (#8)

 

I think I found a workaround but whether it works for you probably depends on how many pages you have to place.

Step 1: split source A4 pdf into 4 sources - 1 for each quadrant.
Easiest way I found so far is by zooming out in the Organize Pages view of Acrobat Pro until you see 4 columns of pages. Drag a selection down until you have the whole column selected.
Extract those selected pages as a new pdf. Repeat that for all 4 columns:

Result:

Step 2: place using MultipageImporter (once for each quadrant)
Set scale to 50%
place first column in top left
second column in top right
and so on:

I generally prefer to create a new layer for each pdf so I can easily get rid of it if something goes wrong.
Result:

Would be great to know if this helps.
Cheers, Mike

**Comment by DL-BL** [comment]
Hi mike

 

No problem! Maybe your first mail already solved my problem!

 

Cheers

Daniel

 

Von: Mike <notifications@github.com>
Antworten an: mike-edel/ID-MultiPageImporter <reply@reply.github.com>
Datum: Samstag, 19. Oktober 2019 um 23:29
An: mike-edel/ID-MultiPageImporter <ID-MultiPageImporter@noreply.github.com>
Cc: Daniel Lauber <d.lauber@datacomm.ch>, Author <author@noreply.github.com>
Betreff: Re: [mike-edel/ID-MultiPageImporter] Placing more then one imported page per new document page. (#8)

 

ps: implementing this could become pretty tricky - and this is more or less the first time I get asked about it.

**Comment by DL-BL** [comment]
Hi Mike!

 

Sorry for my late response!!

 

It was a very busy week. I guess you know that…

 

 

I tried your suggestion with a relatively small file and it was actually quite easy to get the wanted result! Great!

 

We are still waiting on the big files to come in and then they indeed will be urgent 😊

 

But I think it should be doable! Thanks a lot!!

 

Cheers

Daniel

 

Von: Mike <notifications@github.com>
Antworten an: mike-edel/ID-MultiPageImporter <reply@reply.github.com>
Datum: Samstag, 19. Oktober 2019 um 23:26
An: mike-edel/ID-MultiPageImporter <ID-MultiPageImporter@noreply.github.com>
Cc: Daniel Lauber <d.lauber@datacomm.ch>, Author <author@noreply.github.com>
Betreff: Re: [mike-edel/ID-MultiPageImporter] Placing more then one imported page per new document page. (#8)

 

I think I found a workaround but whether it works for you probably depends on how many pages you have to place.

Step 1: split source A4 pdf into 4 sources - 1 for each quadrant.
Easiest way I found so far is by zooming out in the Organize Pages view of Acrobat Pro until you see 4 columns of pages. Drag a selection down until you have the whole column selected.
Extract those selected pages as a new pdf. Repeat that for all 4 columns:

Result:

Step 2: place using MultipageImporter (once for each quadrant)
Set scale to 50%
place first column in top left
second column in top right
and so on:

I generally prefer to create a new layer for each pdf so I can easily get rid of it if something goes wrong.
Result:

Would be great to know if this helps.
Cheers, Mike

**Comment by mike-edel** [comment]
Closing for now as there is a working workaround and there were no further requests like this.
