### ISSUE TITLE
Fit to Margins

### ISSUE THREAD

**Issue by Tomitsch** [mike-edel/ID-MultiPageImporter#9]
Love this, it is super helpful. 

However, I was pulling in 370 pages of web pdfs and wanted to all fit within 1" margins not just the page.  I now have to hand fit all these pages, which is a huge drag.

**Comment by GitBruno** [comment]
I made this work in one version, can’t remember which. Said that, this is also why I added a label to all the places rectangles , so you can post-process them together with the page.side details

‘ "Multi_Page_Importer_Rect"‘

**Comment by mike-edel** [comment]
@Tomitsch My typical approach to this (assuming all pages are the same size) is as follows:
- manually place a single page
- adjust position and size to your liking
- note down the position and scale of the frame (ideally in relation to the top left corner)
- run multipageimporter with the same settings

We do this pretty frequently to insert PDFs inside InDesign based publications (or for interactive PDF usage) and it works fine. 
If your source files have differing sizes you may have to find the correct settings per source format though...
